# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c633925607ec25ef7787a7de4a731ce8404847f5e1052ee757c8e9b6b0819c0148cea0590d377c47804bb57ff01e77ade7f6ebade359aab721cc10ca20627ad

test:
  secret_key_base: c7b49546ac42f266e493818aa5986d55e677cb93e2f447ae7a9c3d796ba2144d0fdb3b6d5e70188124fb2fe95505a37e10372c72e27f218a692afa95f501ddc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
